name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Import gradle properties
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Publish
        run: ./gradlew modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '\n') }}
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          if: success()
          nodetail: true
          title: New build of MiniMap is ready!
          description: |
            Version ${{ env.minecraft_version }} build ${{ github.run_number }}
            Click [here](https://modrinth.com/mod/minimap) to download!
